"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import posixpath

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(__file__))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e9%o_dn_u#-wd#*g2#hde-ypa(odts!rhcvr3j04n(ahb==114'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['http://10.100.0.34', 'http://localhost', 'http://demeter.ciaer.interna',  'https://arq.ciaer.interna']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'app_login.apps.AppLoginConfig',
    'login.apps.LoginConfig',
    'app_arq.apps.AppArqConfig',
    'rolepermissions',

    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    
]

# Configurar a expiração da sessão para 30 minutos (30 * 60 segundos)
SESSION_COOKIE_AGE = 3800

ROOT_URLCONF = 'core.urls'


INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'core.wsgi.application'

from django_auth_ldap.config import *
from django_auth_ldap.config import LDAPSearch

AUTH_LDAP_SERVER_URI = "ldap://10.100.0.1:389"
AUTH_LDAP_BIND_DN = "cn=django,ou=ciaer,dc=ciaer,dc=interna"
AUTH_LDAP_BIND_PASSWORD = "P0rM41s7"

AUTH_LDAP_USER_SEARCH = LDAPSearch(
#            "ou=CIAER,dc=ciaer,dc=interna", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
            "ou=CIAER,dc=ciaer,dc=interna", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"
            )

AUTH_LDAP_USER_ATTR_MAP = {
            "username": "sAMAccountName",
#            "username": "uid",
               "first_name": "name",
                    "last_name": "physicalDeliveryOfficeName",
			#"posto_nome": "cn",
#                        "email": "mail",
}


# AUTHENTICATION_BACKENDS = [
#             'django_auth_ldap.backend.LDAPBackend',
#             'django.contrib.auth.backends.ModelBackend',
# ]

AUTHENTICATION_BACKENDS = [
            'core.backend.CustomLDAPBackend',
                'django.contrib.auth.backends.ModelBackend',
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#   'default': {
#       'ENGINE': 'django.db.backends.sqlite3',
#       'NAME': BASE_DIR / 'db.sqlite3',
#   }
#}

DATABASES = {
      'default': {
          'ENGINE': 'django.db.backends.mysql',
          'NAME': 'arq',
          'USER': 'demeterdb',
          'PASSWORD': 'S1NdemeBD@01',
          'HOST': 'localhost',
          'PORT': '3306'
      }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Caminho para os arquivos estáticos coletados
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    # '/var/www/arq_staticfiles',
]

# Caminho para os arquivos de mídia
MEDIA_URL = '/media/'
# MEDIA_ROOT = '/var/www/doc/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 

# Caminho para os arquivos de mídia
#MEDIA_URL = '/media/'
# MEDIA_ROOT = '/var/www/doc/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ROLEPERMISSIONS_MODULE = "core.roles"

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL ='/'
LOGOUT_REDIRECT_URL = "/"
