# Generated by Django 4.2.10 on 2024-03-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.CharField(max_length=10, null=True, verbose_name='Ano')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'ANO',
                'verbose_name_plural': 'ANOS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caixa', models.CharField(max_length=10, null=True, verbose_name='Caixa')),
                ('caixa_desc', models.CharField(max_length=200, null=True, verbose_name='Caixa Descrição')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fk_ano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.ano', verbose_name='ANO')),
            ],
            options={
                'verbose_name': 'CAIXA',
                'verbose_name_plural': 'CAIXAS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, null=True, verbose_name='Código')),
                ('descritor_do_codigo', models.TextField(blank=True, null=True, verbose_name='Descritor do código')),
                ('fase_corrente_ano', models.IntegerField(blank=True, default=0, null=True, verbose_name='Fase corrente ano')),
                ('fase_corrente_desc', models.TextField(blank=True, null=True, verbose_name='Fase corrente descrição')),
                ('fase_intermediaria_ano', models.IntegerField(blank=True, default=0, null=True, verbose_name='Fase intermediária Ano')),
                ('fase_intermediaria_desc', models.TextField(blank=True, null=True, verbose_name='Fase intermediária descrição')),
                ('destinacao_final_ano', models.IntegerField(blank=True, default=0, null=True, verbose_name='Destinação final ano')),
                ('destinacao_final_desc', models.TextField(blank=True, null=True, verbose_name='Destinação final descrição')),
                ('observacoes_ano', models.IntegerField(blank=True, default=0, null=True, verbose_name='Observações ano')),
                ('observacoes_desc', models.TextField(blank=True, null=True, verbose_name='Observações descrição')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Codigo',
                'verbose_name_plural': 'Codigos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Om',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('om', models.CharField(max_length=20, null=True, verbose_name='OM')),
                ('om_descricao', models.CharField(max_length=200, null=True, verbose_name='OM Descrição')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'OM',
                'verbose_name_plural': 'OMs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10, null=True, verbose_name='Status')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Statu',
                'verbose_name_plural': 'Status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tcu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tcu', models.CharField(max_length=50, null=True, verbose_name='Numero')),
                ('tcu_desc', models.CharField(max_length=200, null=True, verbose_name='Descrição')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'TCU',
                'verbose_name_plural': 'TCUs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, null=True, verbose_name='Tipo')),
                ('tipo_desc', models.CharField(max_length=200, null=True, verbose_name='Tipo Descrição')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'TIPO',
                'verbose_name_plural': 'TIPOS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoGuarda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_guarda_descricao', models.CharField(max_length=50, null=True, verbose_name='Tipo de guarda descrição')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'CAIXA',
                'verbose_name_plural': 'CAIXAS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_data', models.DateField(blank=True, null=True, verbose_name='Data do documento')),
                ('doc_destinacao_final', models.CharField(blank=True, max_length=50, null=True, verbose_name='Destinação final')),
                ('doc_eliminacao_ano', models.IntegerField(blank=True, null=True, verbose_name='Ano de eliminacao')),
                ('doc_corrente_ano', models.IntegerField(blank=True, null=True, verbose_name='Fase corrente anos')),
                ('doc_intermediario_ano', models.IntegerField(blank=True, null=True, verbose_name='Fase intermediaria anos')),
                ('doc_destinacao_final_ano', models.IntegerField(blank=True, null=True, verbose_name='Destinação final anos')),
                ('doc_obs_ano', models.IntegerField(blank=True, null=True, verbose_name='Observação ano')),
                ('doc_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero do documento')),
                ('new_file_sigad', models.CharField(blank=True, max_length=50, null=True, verbose_name='NewFile/SIGAD')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fk_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.caixa', verbose_name='CAIXA')),
                ('fk_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.codigos', verbose_name='CÓDIGO')),
                ('fk_doc_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_doc_destino', to='app_arq.om', verbose_name='DESTINO')),
                ('fk_doc_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_doc_origem', to='app_arq.om', verbose_name='ORIGEM')),
                ('fk_tcu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.tcu', verbose_name='TCU')),
                ('fk_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.tipo', verbose_name='TIPO')),
            ],
            options={
                'verbose_name': 'DOCUMENTO',
                'verbose_name_plural': 'DOCUMENTOS',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='codigos',
            name='fk_tipo_guarda',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_arq.tipoguarda', verbose_name='Tipo de Guarda'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='fk_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.status', verbose_name='Status da caixa'),
        ),
    ]
