# Generated by Django 5.0.3 on 2024-04-10 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ano', models.CharField(max_length=10, verbose_name='Ano')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ano',
                'verbose_name_plural': 'Anos',
            },
        ),
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descritor_do_codigo', models.TextField(verbose_name='Descritor do código')),
                ('fase_corrente_ano', models.IntegerField(blank=True, default=0, verbose_name='Fase corrente ano')),
                ('fase_corrente_desc', models.TextField(blank=True, null=True, verbose_name='Fase corrente descrição')),
                ('fase_intermediaria_ano', models.IntegerField(blank=True, default=0, verbose_name='Fase intermediária ano')),
                ('fase_intermediaria_desc', models.TextField(blank=True, null=True, verbose_name='Fase intermediária descrição')),
                ('destinacao_final_ano', models.IntegerField(blank=True, default=0, verbose_name='Destinação final ano')),
                ('destinacao_final_desc', models.TextField(blank=True, null=True, verbose_name='Destinação final descrição')),
                ('observacoes_ano', models.IntegerField(blank=True, default=0, verbose_name='Observações ano')),
                ('observacoes_desc', models.TextField(blank=True, null=True, verbose_name='Observações descrição')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Código',
                'verbose_name_plural': 'Códigos',
            },
        ),
        migrations.CreateModel(
            name='LogAcaoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('acao', models.CharField(max_length=100, verbose_name='Ação realizada')),
                ('objeto', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField()),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Ação do Usuário',
                'verbose_name_plural': 'Logs de Ações dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='Om',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('om', models.CharField(max_length=200, verbose_name='OM')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'OM',
                'verbose_name_plural': 'OMs',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('caixa', models.CharField(max_length=200, verbose_name='Caixa')),
                ('fk_ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arq.ano', verbose_name='Ano')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('fk_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_arq.status', verbose_name='Status da caixa')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='Tcu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tcu', models.CharField(max_length=250, verbose_name='Número')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'TCU',
                'verbose_name_plural': 'TCUs',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('doc_data', models.DateField(blank=True, null=True, verbose_name='Data do documento')),
                ('doc_destinacao_final', models.CharField(blank=True, max_length=50, verbose_name='Destinação final')),
                ('doc_corrente_ano', models.IntegerField(blank=True, null=True, verbose_name='Fase corrente anos')),
                ('doc_eliminacao_ano', models.IntegerField(blank=True, null=True, verbose_name='Ano de eliminação')),
                ('doc_numero', models.CharField(blank=True, max_length=50, verbose_name='Número do documento')),
                ('new_file_sigad', models.CharField(blank=True, max_length=50, verbose_name='NewFile/SIGAD')),
                ('doc_intermediario_ano', models.IntegerField(blank=True, null=True, verbose_name='Fase intermediária anos')),
                ('doc_destinacao_final_ano', models.IntegerField(blank=True, null=True, verbose_name='Destinação final anos')),
                ('doc_obs_ano', models.IntegerField(blank=True, null=True, verbose_name='Observação ano')),
                ('fk_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.caixa', verbose_name='Caixa')),
                ('fk_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.codigos', verbose_name='Código')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('fk_doc_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_doc_destino', to='app_arq.om', verbose_name='Destino')),
                ('fk_doc_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_doc_origem', to='app_arq.om', verbose_name='Origem')),
                ('fk_tcu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.tcu', verbose_name='TCU')),
                ('fk_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_arq.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoGuarda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo_guarda_descricao', models.CharField(max_length=50, verbose_name='Descrição do tipo de guarda')),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tipo de Guarda',
                'verbose_name_plural': 'Tipos de Guarda',
            },
        ),
        migrations.AddField(
            model_name='codigos',
            name='fk_tipo_guarda',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_arq.tipoguarda', verbose_name='Tipo de Guarda'),
        ),
    ]
