# Generated by Django 5.1.3 on 2025-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_arq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='status_doc',
            field=models.BooleanField(default=False, verbose_name='Conferido'),
        ),
    ]
