# Generated by Django 5.1.3 on 2026-04-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_arq', '0004_alter_ano_create_at_alter_caixa_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cor',
            field=models.CharField(default='#6c757d', help_text='Cor do badge exibido nas listagens (ex: #28a745)', max_length=7, verbose_name='Cor'),
        ),
    ]
